

package io.coredge.health.provide.exception.model;

/**
 * @author suraj
 * 
 * Error codes for the application. 
 * 
 * Parent error code is in 3 digits like MIS-422
 * Aadhar error codes started from - MIS-2001
 * KYC error codes started from - MIS-3001 
 * Email Verification Link error code start from - MIS-600
 *
 */
public enum ErrorCode {

	SYSTEM_EXCEPTION("MIS-500"),
    INVALID_EMAIL_FORMAT("MIS-601"),
    EMAIL_VERIFICATION_EXCEPTION("MIS-602"),
	BUSINESS_EXCEPTION("MIS-422"),
	BAD_REQUEST("EIS-400"),
	UNAUTHORIZED("MIS-401"),
	DATABASE_EXCEPTION("MIS-503"),

	RESOURCE_NOT_FOUND("MIS-1001"),
	FIELD_REQUIRED("MIS-1002"),
	PATTREN_MISMATCHED("MIS-1003"),
	INCORRECT_TYPE("MIS-1004"),
	SIZE_MISMATCHED("MIS-1006"),
	RESOURCE_NOT_AUTHORIZED("MIS-1007"),
	USER_NOT_FOUND("MIS-1008"),

	
	
    INVALID_AUTHENTICATION_METHOD("MIS-1006"),
    RESOURCE_DISABLED("MIS-1007"),
    UIDAI_ERROR("MIS-1009"),
    PASSWORD_MISSMATCH("MIS-1010"), 
    MOBILE_NUMBER_MISSMATCH("MIS-1011"),
    UUID_MISSMATCH("EIS-1000"),
    OTP_MISSMATCH("MIS-1013"),
    ALPHABET_MISSMATCHED("MIS-1014"),
    PHR_ACCOUNT_NOT_AVAILABLE("MIS-1016"),
    HEALTH_ID_NOT_LAUNCHED("MIS-1018"),
    HFR_UID_NOT_AVAILABLE("MIS-1019"),
    HFR_UID_ALREADY_EXIST("MIS-1020"),
    HFR_UID_PASSWORD_NOT_MATCHED("MIS-1021"),
    CAPTCHA_INVALID_EXCEPTION("MIS-1022"),
    OTP_FLOOD_EXCEPTION("MIS-1023"),
    STATE_NOT_VALID_EXCEPTION("MIS-1024"),
    DISTRICT_NOT_VALID_EXCEPTION("MIS-1025"),
    TRANSACTION_NOT_FOUND_EXCEPTION("MIS-1026"),
    HID_BENEFI_NOT_FOUND_EXCEPTION("MIS-1027"),
    AADHAR_NOT_BLANK_EXCEPTION("MIS-1028"),
    HID_ALREADY_EXIST_WITH_AADHAR("MIS-1029"),
    AADHAR_NAME_MISMACTHED_EXCEPTION("MIS-1030"),
    PASSWORD_NOT_SET_EXCEPTION ("MIS-1031"),
    INTEGRATED_PROGRAM_NOT_FOUND_EXCEPTION("MIS-1032"),
    HID_PASSWORD_NOT_MATCHED("MIS-1033"),
    DATE_MISSMATCH("MIS-1034"),
    HEALTH_ID("MIS-1035"),
    INVALID_TRANSACTION_EXCEPTION("MIS-1036"),
    EMPTY_BLANK_EXCEPTION("MIS-1037"),
    MOCKING_EXCEPTION("MIS-1038"),
    USER_BLOCK_EXCEPTION("MIS-1039"),
    IMAGE_VALIDATION_EXCEPTION("MIS-1040"),
    VERIFY_OTP_FLOOD_EXCEPTION("MIS-1041"),
    INVALID_TRANSITION_EXCEPTION("MIS-1042"),
    INCORRECT_REDICT_URL_EXCEPTION("MIS-1043"),
    ACCESS_CODE_EXCEPTION("MIS-1044"),
    MOBILE_UPDATE_FAILED_EXCEPTION("MIS-1045"),
    MOBILE_UPDATE_SAME_FAILED_EXCEPTION("MIS-1046"),
    OTP_PWD_ENC_INVALID_EXCEPTION("MIS-1047"),
    INVALID_TOKEN__EXCEPTION("MIS-1048"),
    CONSENT_EXCEPTION("MIS-1049"),
    MOBILE_NOT_VERIFYIED_EXCEPTION("MIS-1050"),
    BENIFIT_ID_NOT_FOUND_EXCEPTION("MIS-1051"),
    ACCOUNT_ACEEDED_EXCEPTION("MIS-1052"),
    RETRYABLE_EXCEPTION("MIS-1053"),
    INVALID_DOC_TYPE("MIS-1054"),
    HID_CURRENT_OLD_PWD_SAME("MIS-1055"),
    MOBILE_OTP_EXPIRE_EXCEPTION("MIS-1056"),
    VERIFY_OTP_LOCKOUT_EXCEPTION("MIS-1057"),
    MOBILE_NUMBER_NOT_VERIFIED("MIS-1058"),
    PHR_ID_ALREADY_EXISTS("MIS-1059"),
    MOBILE_NUMBER_EMAIL_MISSMATCH("MIS-1060"),
    INVALID_ENCRYPTION_MISSMATCH("MIS-1061"),
    PASSWORD_VERIFICATION_MISSMATCH("MIS-1062"),
    PHR_LOGIN_AUTH_METHOD_NOT_AVAILABLE("MIS-1063"),
    PHR_ACCOUNT_NOT_AVAILABLE_BY_MOBILE("MIS-1064"),
    PHR_ACCOUNT_NOT_AVAILABLE_BY_EMAIL("MIS-1065"),
    PHR_ACCOUNT_NOT_MAPPED_TO_MOBILE("MIS-1066"),
    PHR_ACCOUNT_EDIT_NOT_ALLOWED("MIS-1067"),
    PROFILE_EDIT_LOCKOUT_EXCEPTION("MIS-1068"),
    PASSWORD_SAME_AS_PREVIOUS("MIS-1069"),
    HEALTHIDNUMBER_NOT_FOUND("MIS-1070"),
    UPDATE_OLD_NEW_VALUE_SAME("MIS-1071"),


    INVALID_AADHAR_NUMBER("MIS-2001"),
    UNAUTHORIZED_ASA_MISSMATCH("MIS-2002"),
    UNSPECIFIED_MISSMATCH("MIS-2003"),
	OTP_STORE_MISSMATCH("MIS-2004"),
	BIOMETRIC_LOCK("MIS-2005"),
	UNSUPPORTED_OPTION("MIS-2006"),
	AADHAAR_SUSPENDED("MIS-2007"),
	AADHAAR_CANCELLED("MIS-2008"),
	AADHAAR_SUSPENDED_STATUS("MIS-2009"),
	UNKNOWN_ERROR("MIS-2010"),
	PI_BASIC("MIS-2011"),
	PI_ADDRESS("MIS-2012"),
	BIOMETRC_MISSMATCH("MIS-2013"),
	DUPLICATE_FINGER_MISSMATCH("MIS-2014"),
	DUPLICATE_IRISES_MISSMATCH("MIS-2015"),
	AADHAAR_NUMBER_INVALID("MIS-2016"),
	OTP_FLOOD_AADHAR("MIS-2017"),
	AADHAR_INCORRECT("MIS-2018"),
	AADHAAR_BIOTYPE_INVALID("MIS-2019"),
	
	FMR_FIR_IN_SAME_TXN("MIS-2020"),
	BIOMETRIC_LOCKED_BY_HOLDER("MIS-2021"),
	INVALID_OTP("MIS-2022"),
	TXN_VALUE_MISMATCH("MIS-2023"),
	INVALID_SKEY_ENCRYPTION("MIS-2024"),
	INVALID_CI_VALUE_IN_SKEY("MIS-2025"),
	INVALID_PID_ENCRYPTION("MIS-2026"),
	INVALID_HMAC("MIS-2027"),
	PUBLIC_DEVICES_NOT_ALLOWED("MIS-2028"),
	DEVICES_CERTIFICATE_EXPIRED("MIS-2029"),
	DP_MASTER_CERTIFICATE_EXPIRED("MIS-2030"),
	REQUEST_EXPIRED("MIS-2031"),
	REQUEST_TIME_IN_FUTURE("MIS-2032"),
	DUPLICATE_REQUEST("MIS-2033"),
	HMAC_VALIDATION_FAILED("MIS-2034"),
	AUA_LICENSE_EXPIRED("MIS-2035"),
	INVALID_INPUT("MIS-2036"),
	UNSUPPORTED_LANGUAGE("MIS-2037"),
	DIGITAL_SIGNATURE_FAILED("MIS-2038"),
	INVALID_DIGITAL_SIGN_KEY("MIS-2039"),
	PIN_RESET_REQUIRED("MIS-2040"),
	INVALID_FINGER_POSITION("MIS-2041"),
	FID_USE_NOT_ALLOWED("MIS-2042"),
	NAME_SPACE_NOT_ALLOWED("MIS-2043"),
	REGISTERED_DEVICE_NOT_ALLOWED("MIS-2044"),
	
	DATA_NOT_AVAILABLE("MIS-3001"),
	AUTHENTICATION_FAILURE("MIS-3002"),
	INVALID_VID_NUMBER("MIS-3003"),
    EXPIRED_VID_NUMBER("MIS-3004"),
    MOBILE_NUMBER_NOT_LINKED("MIS-3005"),
    DOCUMENT_VERIFICATION_FAILURE_EXCEPTION("MIS-3006"),
    HID_ALREADY_EXIST("MIS-3007"),
    
    DOCUMENT_MISMATCHED_EXCEPTION("MIS-4000"),
    ALREADY_VERIFIED_ENROLLMENT_NO_EXCEPTION("MIS-4001"),
    ;

	private final String code;

	ErrorCode(String code) {
		this.code = code;
	}

	public String code() {
		return this.code;
	}

}

