/**
 * 
 */
package io.coredge.health.provide.constants;

/**
 * @author Suraj
 *
 */
public interface APIBasePathConstants {


	interface DeveloperMessage {
		String ALPHABET_MISSMATCHED = "ALPHABET_MISSMATCHED";
		String FIELD_REQUIRED = "FIELD_REQUIRED";
		String INCORRECT_TYPE = "INCORRECT_TYPE";
		String MOBILE_NUMBER_MISSMATCH = "MOBILE_NUMBER_MISSMATCH";
		String OTP_MISSMATCH = "OTP_MISSMATCH";
		String PASSWORD_MISSMATCH = "PASSWORD_MISSMATCH";
		String PATTREN_MISMATCHED = "PATTREN_MISMATCHED";
		String SIZE_MISMATCHED = "SIZE_MISMATCHED";
		String UUID_MISSMATCH = "UUID_MISSMATCH";
		String DATE_MISSMATCH = "DATE_MISSMATCH";
		String HEALTH_ID = "HEALTH_ID";
		String AADHAAR_NUMBER_INVALID = "AADHAAR_NUMBER_INVALID";
		String AADHAAR_BIOTYPE_INVALID = "AADHAAR_BIOTYPE_INVALID";
		String INVALID_OIDC_REQUEST_CODE = "INVALID_OIDC_REQUEST_CODE";
		String INVALID_NAME_FORMAT = "INVALID_NAME_FORMAT";
		String INVALID_EMAIL_FORMAT = "INVALID_EMAIL_FORMAT";
		String INVALID_DOC_TYPE = "INVALID_DOC_TYPE";
		String GENDER_INVALID = "GENDER_INVALID";
		String DATA_INVALID = "DATA_INVALID";
		String ENCRYPTION_MISSMATCH = "ENCRYPTION_MISSMATCH";
		String MOBILE_TYPE_INVALID = "MOBILE_TYPE_INVALID";



	}

	interface EndPoints {
		String USER_V1_ENDPOINT = "/v1/user";
		
	}
}
